#ifndef SIGNALBRIDGEPLUGIN_GLOBAL_H
#define SIGNALBRIDGEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALBRIDGEPLUGIN_LIBRARY)
#define SIGNALBRIDGEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#define SIGNALBRIDGEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALBRIDGEPLUGIN_GLOBAL_H
